from __future__ import annotations

from provider_adoption_data.models import ProviderConfig, ProviderPackageConfig


PROVIDER_REGISTRY: tuple[ProviderConfig, ...] = (
    ProviderConfig(
        slug="openai",
        display_name="OpenAI",
        enabled=True,
        pypi_packages=(ProviderPackageConfig("openai", "sdk"),),
        npm_packages=(
            ProviderPackageConfig("openai", "sdk", "core_sdk"),
            ProviderPackageConfig("@openai/agents", "sdk", "agent_sdk"),
            ProviderPackageConfig("@openai/codex", "cli", "cli"),
            ProviderPackageConfig("@openai/codex-sdk", "sdk", "agent_sdk"),
        ),
        huggingface_orgs=("openai", "openai-community"),
        manifest_patterns=("openai",),
        import_patterns=(
            "from openai import",
            "import openai",
            "from \"openai\"",
            "from 'openai'",
            "require(\"openai\")",
            "require('openai')",
        ),
        env_var_patterns=("OPENAI_API_KEY",),
        model_patterns=("gpt-4.1", "gpt-4o", "gpt-4o-mini", "o3", "o4-mini"),
    ),
    ProviderConfig(
        slug="anthropic",
        display_name="Anthropic",
        enabled=True,
        pypi_packages=(ProviderPackageConfig("anthropic", "sdk"),),
        npm_packages=(
            ProviderPackageConfig("@anthropic-ai/sdk", "sdk", "core_sdk"),
            ProviderPackageConfig("@anthropic-ai/claude-agent-sdk", "sdk", "agent_sdk"),
            ProviderPackageConfig("@anthropic-ai/claude-code", "cli", "cli"),
        ),
        huggingface_orgs=("anthropic",),
        manifest_patterns=("anthropic", "@anthropic-ai/sdk"),
        import_patterns=(
            "from anthropic import",
            "import anthropic",
            "@anthropic-ai/sdk",
        ),
        env_var_patterns=("ANTHROPIC_API_KEY",),
        model_patterns=("claude-3-5-sonnet", "claude-3-7-sonnet", "claude-sonnet-4", "claude-opus-4"),
    ),
    ProviderConfig(
        slug="google",
        display_name="Google",
        enabled=True,
        pypi_packages=(
            ProviderPackageConfig("google-genai", "sdk"),
            ProviderPackageConfig("google-generativeai", "legacy_sdk"),
        ),
        npm_packages=(
            ProviderPackageConfig("@google/genai", "sdk", "core_sdk"),
            ProviderPackageConfig("@google/gemini-cli", "cli", "cli"),
            ProviderPackageConfig("@google/generative-ai", "sdk", "legacy_sdk"),
        ),
        huggingface_orgs=("google",),
        manifest_patterns=("google-genai", "google-generativeai", "@google/genai", "@google/generative-ai"),
        import_patterns=(
            "from google import genai",
            "import google.generativeai",
            "@google/genai",
            "@google/generative-ai",
        ),
        env_var_patterns=("GEMINI_API_KEY", "GOOGLE_API_KEY"),
        model_patterns=("gemini-2.5-pro", "gemini-2.5-flash", "gemini-2.0-flash", "gemini-pro"),
    ),
    ProviderConfig(
        slug="deepseek",
        display_name="DeepSeek",
        enabled=True,
        pypi_packages=(),
        npm_packages=(),
        huggingface_orgs=("deepseek-ai",),
        manifest_patterns=(),
        import_patterns=(),
        env_var_patterns=("DEEPSEEK_API_KEY",),
        model_patterns=("deepseek-v3", "deepseek-r1"),
    ),
    ProviderConfig(
        slug="meta",
        display_name="Meta",
        enabled=True,
        pypi_packages=(),
        npm_packages=(),
        huggingface_orgs=("meta-llama",),
        manifest_patterns=(),
        import_patterns=(),
        env_var_patterns=(),
        model_patterns=("llama-3.1", "llama-3.2", "llama-3.3"),
    ),
    ProviderConfig(
        slug="mistral",
        display_name="Mistral",
        enabled=True,
        pypi_packages=(ProviderPackageConfig("mistralai", "sdk"),),
        npm_packages=(ProviderPackageConfig("@mistralai/mistralai", "sdk"),),
        huggingface_orgs=("mistralai",),
        manifest_patterns=("mistralai", "@mistralai/mistralai"),
        import_patterns=("from mistralai", "import mistralai"),
        env_var_patterns=("MISTRAL_API_KEY",),
        model_patterns=("mistral-large", "mistral-small", "pixtral"),
    ),
    ProviderConfig(
        slug="qwen",
        display_name="Qwen",
        enabled=True,
        pypi_packages=(ProviderPackageConfig("dashscope", "sdk"),),
        npm_packages=(),
        huggingface_orgs=("Qwen",),
        manifest_patterns=("dashscope",),
        import_patterns=("import dashscope", "from dashscope import"),
        env_var_patterns=("DASHSCOPE_API_KEY",),
        model_patterns=("qwen2.5", "qwen-max", "qwen-plus", "qwen-turbo"),
    ),
    ProviderConfig(
        slug="moonshot",
        display_name="Moonshot",
        enabled=True,
        pypi_packages=(),
        npm_packages=(),
        huggingface_orgs=("moonshotai",),
        manifest_patterns=(),
        import_patterns=(),
        env_var_patterns=("MOONSHOT_API_KEY",),
        model_patterns=("kimi",),
    ),
    ProviderConfig(
        slug="minimax",
        display_name="Minimax",
        enabled=True,
        pypi_packages=(),
        npm_packages=(),
        huggingface_orgs=("minimaxai",),
        manifest_patterns=(),
        import_patterns=(),
        env_var_patterns=("MINIMAX_API_KEY",),
        model_patterns=(),
    ),
    ProviderConfig(
        slug="zai",
        display_name="ZAI",
        enabled=True,
        pypi_packages=(),
        npm_packages=(),
        huggingface_orgs=("zai-org",),
        manifest_patterns=(),
        import_patterns=(),
        env_var_patterns=(),
        model_patterns=(),
    ),
    ProviderConfig(
        slug="langchain",
        display_name="LangChain",
        enabled=True,
        pypi_packages=(
            ProviderPackageConfig("langchain", "framework", "framework_core"),
            ProviderPackageConfig("langgraph", "framework", "framework_graph"),
        ),
        npm_packages=(
            ProviderPackageConfig("@langchain/core", "framework", "framework_core"),
            ProviderPackageConfig("@langchain/langgraph", "framework", "framework_graph"),
        ),
        huggingface_orgs=(),
        manifest_patterns=("langchain", "langgraph", "@langchain/core", "@langchain/langgraph"),
        import_patterns=("from langchain", "import langchain", "from langgraph", "import langgraph"),
        env_var_patterns=(),
        model_patterns=(),
    ),
    ProviderConfig(
        slug="pydantic_ai",
        display_name="PydanticAI",
        enabled=True,
        pypi_packages=(ProviderPackageConfig("pydantic-ai", "framework", "framework_agent"),),
        npm_packages=(),
        huggingface_orgs=(),
        manifest_patterns=("pydantic-ai",),
        import_patterns=("from pydantic_ai", "import pydantic_ai"),
        env_var_patterns=(),
        model_patterns=(),
    ),
)


def get_provider_registry(provider_slugs: list[str] | None = None) -> tuple[ProviderConfig, ...]:
    active = [provider for provider in PROVIDER_REGISTRY if provider.enabled]
    if provider_slugs:
        wanted = {slug.strip().lower() for slug in provider_slugs if slug.strip()}
        active = [provider for provider in active if provider.slug in wanted]
    return tuple(active)
