from __future__ import annotations


PARENT_SEGMENTS: tuple[str, ...] = (
    "Foundation & model platforms",
    "Data & cloud infrastructure",
    "Developer & data tools",
    "Consumer & services",
    "Fintech & commerce",
    "Chips & compute",
)


# Display-only grouping for cross-company comparisons. The source-level
# company_segment remains the authoritative taxonomy in all normalized data.
PARENT_SEGMENT_BY_COMPANY: dict[str, str] = {
    "openai": "Foundation & model platforms",
    "anthropic": "Foundation & model platforms",
    "perplexity": "Foundation & model platforms",
    "cursor": "Foundation & model platforms",
    "xai": "Foundation & model platforms",
    "cohere": "Foundation & model platforms",
    "together_ai": "Foundation & model platforms",
    "fireworks_ai": "Foundation & model platforms",
    "scale_ai": "Foundation & model platforms",
    "elevenlabs": "Foundation & model platforms",
    "databricks": "Data & cloud infrastructure",
    "mongodb": "Data & cloud infrastructure",
    "cloudflare": "Data & cloud infrastructure",
    "elastic": "Data & cloud infrastructure",
    "dropbox": "Data & cloud infrastructure",
    "supabase": "Data & cloud infrastructure",
    "datadog": "Data & cloud infrastructure",
    "newrelic": "Data & cloud infrastructure",
    "fastly": "Data & cloud infrastructure",
    "okta": "Data & cloud infrastructure",
    "clickhouse": "Data & cloud infrastructure",
    "planetscale": "Data & cloud infrastructure",
    "cockroachlabs": "Data & cloud infrastructure",
    "algolia": "Data & cloud infrastructure",
    "netlify": "Data & cloud infrastructure",
    "fivetran": "Data & cloud infrastructure",
    "snowflake": "Data & cloud infrastructure",
    "confluent": "Data & cloud infrastructure",
    "sentry": "Data & cloud infrastructure",
    "neon": "Data & cloud infrastructure",
    "render": "Data & cloud infrastructure",
    "railway": "Data & cloud infrastructure",
    "airbyte": "Data & cloud infrastructure",
    "motherduck": "Data & cloud infrastructure",
    "pinecone": "Data & cloud infrastructure",
    "weaviate": "Data & cloud infrastructure",
    "gitlab": "Developer & data tools",
    "notion": "Developer & data tools",
    "posthog": "Developer & data tools",
    "asana": "Developer & data tools",
    "vercel": "Developer & data tools",
    "circleci": "Developer & data tools",
    "buildkite": "Developer & data tools",
    "launchdarkly": "Developer & data tools",
    "mixpanel": "Developer & data tools",
    "figma": "Developer & data tools",
    "otter": "Developer & data tools",
    "linear": "Developer & data tools",
    "replit": "Developer & data tools",
    "miro": "Developer & data tools",
    "pinterest": "Consumer & services",
    "reddit": "Consumer & services",
    "twilio": "Consumer & services",
    "lyft": "Consumer & services",
    "instacart": "Consumer & services",
    "roblox": "Consumer & services",
    "airbnb": "Consumer & services",
    "epicgames": "Consumer & services",
    "discord": "Consumer & services",
    "stripe": "Fintech & commerce",
    "coinbase": "Fintech & commerce",
    "brex": "Fintech & commerce",
    "chime": "Fintech & commerce",
    "monzo": "Fintech & commerce",
    "plaid": "Fintech & commerce",
    "nubank": "Fintech & commerce",
    "graphcore": "Chips & compute",
    "lightmatter": "Chips & compute",
    "cerebras": "Chips & compute",
    "modal": "Chips & compute",
}


def parent_segment_for_company(company_id: str) -> str:
    return PARENT_SEGMENT_BY_COMPANY.get(str(company_id), "Unmapped")
